spring:
  profiles:
    active: dev
  application:
    name: springcloud-eureka

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone:  http://${security.user.name}:${security.user.password}@localhost:8761/eureka
security:
  basic:
    enabled: true
  user:
    name: user
    password: 123456
        
#日志配置
logging:
  file: springcloud-eureka.log
  level.org.springframework.web: info
  debug: false

---
spring:
  profiles: dev

    
---
spring:
  profiles: prod
