server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    
#日志配置
logging:
  file: springcloud-eureka.log
  level.org.springframework.web: info
  debug: false

