security:
  basic:
    enabled: true
  user:
    name: user
    password: 123456
        
#日志配置
logging:
  file: springcloud-eureka.log
  level.org.springframework.web: info
  debug: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

